apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "web-status-checker.fullname" . }}
    labels:
        {{ include "web-status-checker.labels" . | indent 4 }}
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app.kubernetes.io/name: {{ include "web-status-checker.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
    template:
        metadata:
            labels:
                app.kubernetes.io/name: {{ include "web-status-checker.name" . }}
                app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
                {{- with .Values.imagePullSecrets }}
            imagePullSecrets:
                {{- toYaml . | nindent 8 }}
                {{- end }}
            containers:
                - name: {{ .Chart.Name }}
                  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                  imagePullPolicy: {{ .Values.image.pullPolicy }}

                  env:
                          {{- range $env_key, $env_value := .Values.environment_variables }}
                      - name: {{ $env_key | quote }}
                        value: {{ $env_value | quote }}
                        {{- end }}
                  ports:
                      - name: http
                        containerPort: 8080
                        protocol: TCP
                  livenessProbe:
                      httpGet:
                          path: /metrics
                          port: http
                  readinessProbe:
                      httpGet:
                          path: /metrics
                          port: http
                  resources:
                {{- toYaml .Values.resources | nindent 12 }}
                {{- with .Values.nodeSelector }}
            nodeSelector:
                {{- toYaml . | nindent 8 }}
                {{- end }}
                {{- with .Values.affinity }}
            affinity:
                {{- toYaml . | nindent 8 }}
                {{- end }}
                {{- with .Values.tolerations }}
            tolerations:
            {{- toYaml . | nindent 8 }}
        {{- end }}
